# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\PoseUI\widgets\ui\action_followP2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Action_FollowP2(object):
    def setupUi(self, Action_FollowP2):
        Action_FollowP2.setObjectName("Action_FollowP2")
        Action_FollowP2.resize(1920, 1080)
        self.lab_title = QtWidgets.QLabel(Action_FollowP2)
        self.lab_title.setGeometry(QtCore.QRect(1525, 80, 390, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lab_title.setFont(font)
        self.lab_title.setStyleSheet("background-color: rgb(5,40,87);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"")
        self.lab_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_title.setObjectName("lab_title")
        self.lab_text = QtWidgets.QLabel(Action_FollowP2)
        self.lab_text.setGeometry(QtCore.QRect(1528, 505, 390, 575))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        self.lab_text.setFont(font)
        self.lab_text.setStyleSheet("background-color:rgb(5,40,87);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.lab_text.setText("")
        self.lab_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lab_text.setWordWrap(True)
        self.lab_text.setObjectName("lab_text")
        self.control_frame = QtWidgets.QFrame(Action_FollowP2)
        self.control_frame.setGeometry(QtCore.QRect(1540, 10, 371, 50))
        self.control_frame.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"\n"
"QFrame{\n"
"background-color: rgba(5,40,87,0);\n"
"}")
        self.control_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_frame.setObjectName("control_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.control_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_stoporplay = QtWidgets.QPushButton(self.control_frame)
        self.btn_stoporplay.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_stoporplay.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_stoporplay.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/figs/icon/menu_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stoporplay.setIcon(icon)
        self.btn_stoporplay.setIconSize(QtCore.QSize(35, 35))
        self.btn_stoporplay.setObjectName("btn_stoporplay")
        self.horizontalLayout.addWidget(self.btn_stoporplay)
        self.btn_replay = QtWidgets.QPushButton(self.control_frame)
        self.btn_replay.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_replay.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_replay.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/background/figs/icon/重新加载.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_replay.setIcon(icon1)
        self.btn_replay.setIconSize(QtCore.QSize(40, 40))
        self.btn_replay.setObjectName("btn_replay")
        self.horizontalLayout.addWidget(self.btn_replay)
        self.btn_exit = QtWidgets.QPushButton(self.control_frame)
        self.btn_exit.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_exit.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_exit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/figs/icon/menu_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon2)
        self.btn_exit.setIconSize(QtCore.QSize(40, 40))
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout.addWidget(self.btn_exit)
        self.pose_frame = QtWidgets.QFrame(Action_FollowP2)
        self.pose_frame.setGeometry(QtCore.QRect(1520, 120, 400, 400))
        self.pose_frame.setStyleSheet("border-bottom-left-radius:10px;\n"
"border-top-left-radius:10px;\n"
"")
        self.pose_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pose_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pose_frame.setObjectName("pose_frame")

        self.retranslateUi(Action_FollowP2)
        QtCore.QMetaObject.connectSlotsByName(Action_FollowP2)

    def retranslateUi(self, Action_FollowP2):
        _translate = QtCore.QCoreApplication.translate
        Action_FollowP2.setWindowTitle(_translate("Action_FollowP2", "Form"))
        self.lab_title.setText(_translate("Action_FollowP2", " 第1课 擒敌拳"))
import res_rc
