# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PoseUI\PoseUI\widgets\ui\center_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Center_Menu(object):
    def setupUi(self, Center_Menu):
        Center_Menu.setObjectName("Center_Menu")
        Center_Menu.resize(1920, 1080)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Center_Menu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.base_frame = QtWidgets.QFrame(Center_Menu)
        self.base_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"\n"
"")
        self.base_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base_frame.setObjectName("base_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.base_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sub_frame_1 = QtWidgets.QFrame(self.base_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sub_frame_1.setFont(font)
        self.sub_frame_1.setStyleSheet("QToolButton:hover{\n"
"border:none;\n"
"background-color:rgb(0, 47, 167);\n"
"}\n"
"\n"
"QToolButton{\n"
"border:none;\n"
"background-color:rgb(0, 49, 83);\n"
"}\n"
"")
        self.sub_frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sub_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sub_frame_1.setObjectName("sub_frame_1")
        self.gridLayout = QtWidgets.QGridLayout(self.sub_frame_1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 6, 1, 1)
        self.btn_rea_train = QtWidgets.QToolButton(self.sub_frame_1)
        self.btn_rea_train.setMinimumSize(QtCore.QSize(200, 200))
        self.btn_rea_train.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.btn_rea_train.setFont(font)
        self.btn_rea_train.setStyleSheet("QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    padding:20px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/figs/icon/对抗训练.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rea_train.setIcon(icon)
        self.btn_rea_train.setIconSize(QtCore.QSize(100, 100))
        self.btn_rea_train.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_rea_train.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_rea_train.setObjectName("btn_rea_train")
        self.gridLayout.addWidget(self.btn_rea_train, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        self.btn_std_train = QtWidgets.QToolButton(self.sub_frame_1)
        self.btn_std_train.setMinimumSize(QtCore.QSize(200, 200))
        self.btn_std_train.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.btn_std_train.setFont(font)
        self.btn_std_train.setStyleSheet("QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    padding:20px;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/figs/icon/跟随训练.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_std_train.setIcon(icon1)
        self.btn_std_train.setIconSize(QtCore.QSize(100, 100))
        self.btn_std_train.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_std_train.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_std_train.setObjectName("btn_std_train")
        self.gridLayout.addWidget(self.btn_std_train, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.btn_grade = QtWidgets.QToolButton(self.sub_frame_1)
        self.btn_grade.setMinimumSize(QtCore.QSize(200, 200))
        self.btn_grade.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.btn_grade.setFont(font)
        self.btn_grade.setStyleSheet("QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    padding:20px;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/figs/icon/118评估.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_grade.setIcon(icon2)
        self.btn_grade.setIconSize(QtCore.QSize(100, 100))
        self.btn_grade.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_grade.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_grade.setObjectName("btn_grade")
        self.gridLayout.addWidget(self.btn_grade, 1, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 3, 1, 1)
        self.verticalLayout.addWidget(self.sub_frame_1)
        self.sub_frame_2 = QtWidgets.QFrame(self.base_frame)
        self.sub_frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.sub_frame_2.setSizeIncrement(QtCore.QSize(0, 150))
        self.sub_frame_2.setStyleSheet("QToolButton:hover{\n"
"border:none;\n"
"background-color:rgb(0, 47, 167);\n"
"}\n"
"\n"
"QToolButton{\n"
"border:none;\n"
"background-color:rgb(0, 49, 83);\n"
"}\n"
"")
        self.sub_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sub_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sub_frame_2.setObjectName("sub_frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sub_frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btn_back = QtWidgets.QPushButton(self.sub_frame_2)
        self.btn_back.setMinimumSize(QtCore.QSize(300, 100))
        self.btn_back.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgba(50, 50, 50,0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/figs/icon/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon3)
        self.btn_back.setIconSize(QtCore.QSize(45, 45))
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_3.addWidget(self.btn_back)
        spacerItem7 = QtWidgets.QSpacerItem(600, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.btn_setting = QtWidgets.QPushButton(self.sub_frame_2)
        self.btn_setting.setMinimumSize(QtCore.QSize(200, 80))
        self.btn_setting.setMaximumSize(QtCore.QSize(200, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.btn_setting.setFont(font)
        self.btn_setting.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"background-color: rgba(50, 50, 50,0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/figs/icon/设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting.setIcon(icon4)
        self.btn_setting.setIconSize(QtCore.QSize(30, 30))
        self.btn_setting.setObjectName("btn_setting")
        self.horizontalLayout_3.addWidget(self.btn_setting)
        self.verticalLayout.addWidget(self.sub_frame_2)
        self.horizontalLayout.addWidget(self.base_frame)

        self.retranslateUi(Center_Menu)
        QtCore.QMetaObject.connectSlotsByName(Center_Menu)

    def retranslateUi(self, Center_Menu):
        _translate = QtCore.QCoreApplication.translate
        Center_Menu.setWindowTitle(_translate("Center_Menu", "Form"))
        self.btn_rea_train.setText(_translate("Center_Menu", "动作反应训练"))
        self.btn_std_train.setText(_translate("Center_Menu", "动作规范训练"))
        self.btn_grade.setText(_translate("Center_Menu", "成绩查询"))
        self.btn_back.setText(_translate("Center_Menu", "返回登录界面"))
        self.btn_setting.setText(_translate("Center_Menu", "系统设置"))
import res_rc
