# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PoseUI\PoseUI\widgets\ui\login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(900, 600)
        Login.setMinimumSize(QtCore.QSize(900, 600))
        Login.setMaximumSize(QtCore.QSize(900, 600))
        self.loginwidget = QtWidgets.QWidget(Login)
        self.loginwidget.setObjectName("loginwidget")
        self.back1 = QtWidgets.QLabel(self.loginwidget)
        self.back1.setGeometry(QtCore.QRect(150, 120, 600, 400))
        self.back1.setStyleSheet("border-image:url(:/background/figs/other_resources/mian_log.png);\n"
"border-radius:20px;\n"
"")
        self.back1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.back1.setLineWidth(0)
        self.back1.setText("")
        self.back1.setObjectName("back1")
        self.back2 = QtWidgets.QLabel(self.loginwidget)
        self.back2.setGeometry(QtCore.QRect(380, 180, 131, 61))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.back2.setFont(font)
        self.back2.setStyleSheet("color: rgb(255, 255, 255);")
        self.back2.setLineWidth(0)
        self.back2.setAlignment(QtCore.Qt.AlignCenter)
        self.back2.setObjectName("back2")
        self.lab_camera = QtWidgets.QLabel(self.loginwidget)
        self.lab_camera.setGeometry(QtCore.QRect(390, 260, 110, 110))
        self.lab_camera.setMinimumSize(QtCore.QSize(110, 110))
        self.lab_camera.setMaximumSize(QtCore.QSize(110, 110))
        self.lab_camera.setStyleSheet("")
        self.lab_camera.setText("")
        self.lab_camera.setPixmap(QtGui.QPixmap(":/icons/figs/icon/user110.png"))
        self.lab_camera.setObjectName("lab_camera")
        self.log_opt = QtWidgets.QFrame(self.loginwidget)
        self.log_opt.setGeometry(QtCore.QRect(300, 400, 300, 50))
        self.log_opt.setStyleSheet("QPushButton{\n"
"  border:none;\n"
"  color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" padding-bottom:4px;\n"
"}\n"
"")
        self.log_opt.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.log_opt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.log_opt.setObjectName("log_opt")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.log_opt)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_open = QtWidgets.QPushButton(self.log_opt)
        self.btn_open.setMinimumSize(QtCore.QSize(120, 40))
        self.btn_open.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/figs/icon/相机.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open.setIcon(icon)
        self.btn_open.setIconSize(QtCore.QSize(20, 20))
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout.addWidget(self.btn_open)
        self.btn_close = QtWidgets.QPushButton(self.log_opt)
        self.btn_close.setEnabled(True)
        self.btn_close.setMinimumSize(QtCore.QSize(120, 40))
        self.btn_close.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_close.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/figs/icon/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setIconSize(QtCore.QSize(20, 20))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.logo = QtWidgets.QPushButton(self.loginwidget)
        self.logo.setGeometry(QtCore.QRect(160, 130, 250, 50))
        self.logo.setMinimumSize(QtCore.QSize(250, 50))
        self.logo.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.logo.setFont(font)
        self.logo.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);")
        self.logo.setIconSize(QtCore.QSize(30, 30))
        self.logo.setObjectName("logo")
        Login.setCentralWidget(self.loginwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.back2.setText(_translate("Login", "欢迎登录"))
        self.btn_open.setText(_translate("Login", "打开相机"))
        self.btn_close.setText(_translate("Login", "退出系统"))
        self.logo.setText(_translate("Login", "警察执法动作规范与反应评估系统"))
import res_rc
