# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_background.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Background(object):
    def setupUi(self, Login_Background):
        Login_Background.setObjectName("Login_Background")
        Login_Background.resize(1920, 1080)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Login_Background)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Login_Background)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(Login_Background)
        QtCore.QMetaObject.connectSlotsByName(Login_Background)

    def retranslateUi(self, Login_Background):
        _translate = QtCore.QCoreApplication.translate
        Login_Background.setWindowTitle(_translate("Login_Background", "Form"))
