# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\test\PoseUI\widgets\ui\reaction_train_playerP3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reaction_Train_PlayerP3(object):
    def setupUi(self, Reaction_Train_PlayerP3):
        Reaction_Train_PlayerP3.setObjectName("Reaction_Train_PlayerP3")
        Reaction_Train_PlayerP3.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Reaction_Train_PlayerP3.sizePolicy().hasHeightForWidth())
        Reaction_Train_PlayerP3.setSizePolicy(sizePolicy)
        self.feed_frame = QtWidgets.QFrame(Reaction_Train_PlayerP3)
        self.feed_frame.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feed_frame.sizePolicy().hasHeightForWidth())
        self.feed_frame.setSizePolicy(sizePolicy)
        self.feed_frame.setStyleSheet("QFrame{\n"
"background-color: qradialgradient(spread:pad, \n"
"cx:0.5, cy:0.5, radius:0.9, fx:0.5, fy:0.5, \n"
"stop:0 rgba(0, 0, 0, 0), stop:1 rgba(200, 0, 0, 255)); \n"
"}")
        self.feed_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.feed_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.feed_frame.setObjectName("feed_frame")

        self.retranslateUi(Reaction_Train_PlayerP3)
        QtCore.QMetaObject.connectSlotsByName(Reaction_Train_PlayerP3)

    def retranslateUi(self, Reaction_Train_PlayerP3):
        _translate = QtCore.QCoreApplication.translate
        Reaction_Train_PlayerP3.setWindowTitle(_translate("Reaction_Train_PlayerP3", "Form"))
import res_rc
