# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PoseUI\PoseUI\widgets\ui\std_train_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Std_Train_Select(object):
    def setupUi(self, Std_Train_Select):
        Std_Train_Select.setObjectName("Std_Train_Select")
        Std_Train_Select.resize(1920, 1080)
        self.gridLayout = QtWidgets.QGridLayout(Std_Train_Select)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.base_frame = QtWidgets.QFrame(Std_Train_Select)
        self.base_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"\n"
"")
        self.base_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base_frame.setObjectName("base_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.base_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sub_frame_1 = QtWidgets.QFrame(self.base_frame)
        self.sub_frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sub_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sub_frame_1.setObjectName("sub_frame_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sub_frame_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lab_name = QtWidgets.QLabel(self.sub_frame_1)
        self.lab_name.setMinimumSize(QtCore.QSize(200, 40))
        self.lab_name.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.lab_name.setFont(font)
        self.lab_name.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 170, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.lab_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_name.setObjectName("lab_name")
        self.gridLayout_2.addWidget(self.lab_name, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 350, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 4, 1, 1)
        self.btn_ac_train = QtWidgets.QToolButton(self.sub_frame_1)
        self.btn_ac_train.setMinimumSize(QtCore.QSize(200, 200))
        self.btn_ac_train.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.btn_ac_train.setFont(font)
        self.btn_ac_train.setStyleSheet("QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    padding:20px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"border:none;\n"
"background-color:rgb(250, 153, 47);\n"
"}\n"
"\n"
"QToolButton{\n"
"border:none;\n"
"background-color:rgb(220, 153, 47);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/figs/icon/跑步.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ac_train.setIcon(icon)
        self.btn_ac_train.setIconSize(QtCore.QSize(100, 100))
        self.btn_ac_train.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_ac_train.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_ac_train.setObjectName("btn_ac_train")
        self.gridLayout_2.addWidget(self.btn_ac_train, 3, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.btn_ac_analysis = QtWidgets.QToolButton(self.sub_frame_1)
        self.btn_ac_analysis.setMinimumSize(QtCore.QSize(200, 200))
        self.btn_ac_analysis.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.btn_ac_analysis.setFont(font)
        self.btn_ac_analysis.setStyleSheet("QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    padding:20px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"border:none;\n"
"background-color:rgb(218, 48, 37);\n"
"}\n"
"\n"
"QToolButton{\n"
"border:none;\n"
"background-color:rgb(188, 48, 37);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/figs/icon/分析.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ac_analysis.setIcon(icon1)
        self.btn_ac_analysis.setIconSize(QtCore.QSize(100, 100))
        self.btn_ac_analysis.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btn_ac_analysis.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_ac_analysis.setObjectName("btn_ac_analysis")
        self.gridLayout_2.addWidget(self.btn_ac_analysis, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.sub_frame_1)
        self.sub_frame_2 = QtWidgets.QFrame(self.base_frame)
        self.sub_frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.sub_frame_2.setSizeIncrement(QtCore.QSize(0, 150))
        self.sub_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sub_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sub_frame_2.setObjectName("sub_frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sub_frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.btn_back = QtWidgets.QPushButton(self.sub_frame_2)
        self.btn_back.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_back.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgba(50, 50, 50,0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/figs/icon/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon2)
        self.btn_back.setIconSize(QtCore.QSize(45, 45))
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_3.addWidget(self.btn_back)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.sub_frame_2)
        self.gridLayout.addWidget(self.base_frame, 0, 0, 1, 1)

        self.retranslateUi(Std_Train_Select)
        QtCore.QMetaObject.connectSlotsByName(Std_Train_Select)

    def retranslateUi(self, Std_Train_Select):
        _translate = QtCore.QCoreApplication.translate
        Std_Train_Select.setWindowTitle(_translate("Std_Train_Select", "Form"))
        self.lab_name.setText(_translate("Std_Train_Select", "擒敌拳"))
        self.btn_ac_train.setText(_translate("Std_Train_Select", "跟随训练"))
        self.btn_ac_analysis.setText(_translate("Std_Train_Select", "动作分析"))
        self.btn_back.setText(_translate("Std_Train_Select", "返回"))
import res_rc
