# Setting
gpus: [0]
seed: 1
pretrained_path: .\auxiliary_tools\action_model\model\2022-12-03 22-08-56\2001_EfficientGCN-B0_ntu-xsub120.pth.tar
# Model
model_type: EfficientGCN-B0
model_args:
  stem_channel: 64
  block_args: [[48,1,0.5],[24,1,0.5],[64,2,1],[128,2,1]]
  fusion_stage: 2
  act_type: swish
  att_type: stja
  layer_type: Sep
  drop_prob: 0.25
  kernel_size: [5,2]
  scale_args: [1.2,1.35]
  expand_ratio: 2
  reduct_ratio: 4
  bias: True
  edge: True


